[package]
name = "quick_server"
description = "base native libs"
version = "0.0.0"
authors = ["sanmu <hdy9515@dingtalk.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

